# Generated by Django 5.0.6 on 2024-06-15 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Color_Data', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color_value',
        ),
    ]
