# Generated by Django 5.0.6 on 2024-06-17 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Color_Data', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
